version: "3.9"

services:
  x-dns:
    build: .
    container_name: x-dns
    restart: unless-stopped
    ports:
      - "53:53/udp"
    cap_add:
      - NET_BIND_SERVICE
    # kalau di Linux, kadang perlu privileged
    # privileged: true
